### PR TITLE
User primary search icon if search is not empty

### PR DESCRIPTION
**Pull request by smiclea**
When searching for a replica, migration or endpoint, don't reset the
search icon's color to grey when leaving the search input if the search
input is not empty. Thus, it is much clearer if the list items are
filtered or not.

### CODE REVIEW

**Comment by thenoizz** [comment]
I would leave the search box open for the entire time the list is filtered. Also we need a clear button in the search box.

**Comment by smiclea** [comment]
The clear button for the search input is available as part of the azure-migrate PR, we can extract it though, if necessary. 
I will make the search input stay open though.

**Comment by thenoizz** [comment]
@smiclea let's add the button on a separate pr

**Comment by smiclea** [comment]
Ok, will do.

**Pull request merged**
