### PR TITLE
Improve wizard instances search loading and pagination CORWEB-39 CORWEB-78

### PR DESCRIPTION
**Pull request by smiclea**
Don't blank the instances list while searching, instead show a loading spinner in the search box.
Don't blank the instances list while changing the page, instead show loading spinner.
Small WizardVms.js and SearchBox.js refactoring.
Fix JS error with caching and pagination.

### CODE REVIEW

**Comment by thenoizz** [comment]
La next page cred ca ar fi bine sa punem spinnerul altundeva. Am sa-ti trimit mockup.

**Comment by thenoizz** [comment]
605-migrationwizard copy
605-migrationwizard

**Comment by smiclea** [comment]
Sounds good!

**Comment by thenoizz** [comment]
Ok, 2 small nits
1: I have horiz. scrollbars
screenshot 2017-09-19 14 43 53

2:
For refresh we should use the same stuff as for next page and go to page 1.
screenshot 2017-09-19 14 43 57

**Pull request merged**
