### PR TITLE
Add ability to export / import endpoints from JSON

### PR DESCRIPTION
**Pull request by smiclea**
Endpoints can be exported in bulk from the endpoints list or
individually from their details page.

An endpoint can be imported from a JSON file by choosing New Endpoint
from the dropdown input.

### CODE REVIEW

**Comment by thenoizz** [comment]
How do we handle multiple endpoints exports? Right now it seems that it is downloading only items.

**Comment by thenoizz** [comment]
Check also if the endpoint type is supported before validating

**Comment by smiclea** [comment]
New file extension is now used: `.endpoint` instead of `.json`.

Providers are now validating before allowing `.endpoint` file import.

When downloading multiple selected endpoints, a zip is used to archive all the corresponding `.endpoint` files.

**Comment by aznashwan** [comment]
Tested and works. Merging. Thanks!

**Pull request merged**
