### PR TITLE
Poll replica status if current status is running CORWEB-23

### PR DESCRIPTION
**Pull request by smiclea**
Reset the open state of the running execution's rows to keep only the running tasks open.

### CODE REVIEW

**Comment by thenoizz** [comment]
Can you pls do rebase? Thx :-)

**Comment by smiclea** [comment]
Rebased.

**Comment by alexpilotti** [comment]
Can we put jira references in the PR instead of the commit messages?

**Comment by smiclea** [comment]
Yes, sure. Will do!

**Pull request merged**
