### PR TITLE
Refactor and restyle the options page according to design CORWEB-18

### PR DESCRIPTION
**Pull request by smiclea**
Implemented ability to add description to fields and display it in tooltips. Also added a mockup description for 'flavor_name'.

Use a switch component for all boolean fields. Refactored ConnectionStore.js to no longer convert boolean fields to strings.

Use the switch component to switch between simple and advanced options.

Refactored wizard's options style to no longer use floats, instead use CSS Flex.

Removed unused variable in WizardSummary.

### CODE REVIEW

**Comment by thenoizz** [comment]
Conflicts :-)

**Comment by smiclea** [comment]
Rebased.

**Comment by thenoizz** [comment]
Looks very nice ! Kudos
Some nits: 

1. When there are only up to 4 options, can we pls put them centered? I've attached some screens, but you can find them in the sketch

2. Tooltips should be on all items

**Comment by smiclea** [comment]
Regarding 2., currently a tooltip is shown for a field only if there's a _description_ for it (descriptions can be set in CloudLabels.js for all fields). I've only added a description for '_flavor_name_', that's why only that field's tooltip is visible.

To show tooltips for all fields, description needs to be filled for all fields. I would be happy to do that if I'd know what description to put there.

**Comment by thenoizz** [comment]
Perfect!

On 27 Sep 2017, at 13:27, Sergiu Miclea <notifications@github.com<mailto:notifications@github.com>> wrote:


Regarding 2., currently a tooltip is shown for a field only if there's a description for it (descriptions can be set in CloudLabels.js for all fields). I've only added a description for 'flavor_name', that's why only that field's tooltip is visible.

To show tooltips for all fields, description needs to be filled for all fields. I would be happy to do that if I'd know what description to put there.

**Pull request merged**
